# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oxqsaZEH81ofuq2tVEHcdQ2MCSNr1itU
"""

# --- Pierwszy blok kodu: Import bibliotek ---
import os
import requests
from dotenv import load_dotenv
from bs4 import BeautifulSoup
from IPython.display import Markdown, display
import ollama

# --- Drugi blok kodu: Test działania modelu ---
message = "Tell me something about transformer technology"
response = ollama.chat(model='llama3.2', messages=[{"role": "user", "content": message}])
print(response['message']['content'])

# --- Trzeci blok kodu: Klasa web scrapera ---
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
}

class Website:
    def __init__(self, url):
        self.url = url
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.content, 'html.parser')
        self.title = soup.title.string if soup.title else "No title found"
        for irrelevant in soup.body(["script", "style", "img", "input", "link"]):
            irrelevant.decompose()
        self.text = soup.body.get_text(separator="\n", strip=True)

# --- Czwarty blok kodu: Test klasy Website ---
web = Website("https://en.wikipedia.org/wiki/Large_language_model")
print("Title:", web.title)
print("Text:", web.text)

# --- Piąty blok kodu: Prompt systemowy ---
system_prompt = "You are an assistant that analyzes the contents of a website and provides a short summary, ignoring text that might be navigation related. Respond in markdown."

# --- Szósty blok kodu: Prompt użytkownika ---
def user_prompt_for(website):
    user_prompt = f"You are looking at a website titled {website.title}.\n"
    user_prompt += "The contents of this website is as follows:\n"
    user_prompt += "Please provide a short summary of this website in markdown.\n"
    user_prompt += "If it includes news or announcements, then summarize these too.\n\n"
    user_prompt += website.text
    return user_prompt

# --- Siódmy blok kodu: Struktura wiadomości dla API ---
def messages_for(website):
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt_for(website)}
    ]

# --- Ósmy blok kodu: Funkcja podsumowująca ---
MODEL = "llama3.2"

def summarize(url):
    website = Website(url)
    response = ollama.chat(
        model=MODEL,
        messages=messages_for(website)
    )
    return response['message']['content']

# --- Dziewiąty blok kodu: Wyświetlanie w formacie Markdown ---
def display_summary(url):
    summary = summarize(url)
    display(Markdown(summary))

# --- Ostatnia linia: Wywołanie podsumowania dla konkretnej strony ---
display_summary("https://wp.pl")